name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # CI job for testing the Laravel application
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Update to your PHP version
          extensions: mbstring, bcmath, zip, sqlite, pdo, gd, curl
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-scripts --no-interaction
          cp .env.example .env
          php artisan key:generate

      - name: Run tests
        run: |
          vendor/bin/phpunit --configuration phpunit.xml

  # CD job for deployment to DigitalOcean
  deploy:
    runs-on: ubuntu-latest
    needs: ci  # Ensure deployment only runs after tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Update to your PHP version
          extensions: mbstring, bcmath, zip, sqlite, pdo, gd, curl

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-scripts --no-interaction
          cp .env.example .env
          php artisan key:generate

      - name: Deploy Laravel application to DigitalOcean
        run: |
          ssh user@digitalocean-ip "cd /var/www/laravel-app && git pull origin main && composer install --no-dev && php artisan migrate --force && php artisan config:cache"
